name: Docker Image CI

on:
  push:
    branches: [ "image-build" ]
  pull_request:
    branches: [ "image-build" ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  DOCKERFILE_NAME: "Dockerfile"
  DOCKER_IMAGE_NAME: "imageName"
  DOCKER_IMAGE_VERSION: "latest"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE_NAME --tag $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
    - name: Push Docker image to AliYun
      run: docker push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
